language: ruby
cache: bundler
rbenv:
- 2.5.3
before_install:
- gem install bundler
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec