langauge: ruby
rvm:
  - 2.5
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
before_install:
  - yes | gem update --system --force
  - gem install bundler